/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Bugsink
 * Bugsink API Documentation
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * LIST requires: ?issue=<uuid>
Optional: ?order=asc|desc   (default: desc)
LIST omits `data`, ordered by digest_order
RETRIEVE includes `data` (pure PK lookup; no filters/order applied)
 */
export const EventsListQueryParams = zod.object({
  "cursor": zod.string().optional().describe('The pagination cursor value.'),
  "issue": zod.uuid().describe('Filter events by issue UUID (required).'),
  "order": zod.enum(['asc', 'desc']).optional().describe('Sort order of digest_order (default: desc).')
})

export const eventsListResponseResultsItemDigestOrderMin = 0;
export const eventsListResponseResultsItemDigestOrderMax = 2147483647;



export const EventsListResponse = zod.object({
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.uuid().describe('Bugsink-internal'),
  "ingested_at": zod.iso.datetime({}),
  "digested_at": zod.iso.datetime({}),
  "issue": zod.uuid(),
  "grouping": zod.number(),
  "event_id": zod.uuid().describe('As per the sent data'),
  "project": zod.number(),
  "timestamp": zod.iso.datetime({}),
  "digest_order": zod.number().min(eventsListResponseResultsItemDigestOrderMin).max(eventsListResponseResultsItemDigestOrderMax)
}).describe('Lightweight list view: excludes the (potentially large) `data` field.'))
})


/**
 * LIST requires: ?issue=<uuid>
Optional: ?order=asc|desc   (default: desc)
LIST omits `data`, ordered by digest_order
RETRIEVE includes `data` (pure PK lookup; no filters/order applied)
 */
export const EventsRetrieveParams = zod.object({
  "id": zod.uuid()
})

export const eventsRetrieveResponseDigestOrderMin = 0;
export const eventsRetrieveResponseDigestOrderMax = 2147483647;



export const EventsRetrieveResponse = zod.object({
  "id": zod.uuid().describe('Bugsink-internal'),
  "ingested_at": zod.iso.datetime({}),
  "digested_at": zod.iso.datetime({}),
  "issue": zod.uuid(),
  "grouping": zod.number(),
  "event_id": zod.uuid().describe('As per the sent data'),
  "project": zod.number(),
  "timestamp": zod.iso.datetime({}),
  "digest_order": zod.number().min(eventsRetrieveResponseDigestOrderMin).max(eventsRetrieveResponseDigestOrderMax),
  "data": zod.unknown(),
  "stacktrace_md": zod.string()
}).describe('Detail view: includes full `data` payload.')


/**
 * Render the event's stacktrace (frames, source, locals) as Markdown-like text.
 */
export const EventsStacktraceRetrieveParams = zod.object({
  "id": zod.uuid()
})


/**
 * LIST requires: ?project=<uuid>
Optional: ?order=asc|desc        (default: desc)
LIST ordered by last_seen
RETRIEVE is a pure PK lookup (soft-deletes implied)
 */
export const IssuesListQueryParams = zod.object({
  "cursor": zod.string().optional().describe('The pagination cursor value.'),
  "order": zod.enum(['asc', 'desc']).optional().describe('Sort order (default: asc).'),
  "project": zod.number().describe('Filter issues by project id (required).'),
  "sort": zod.enum(['digest_order', 'last_seen']).optional().describe('Sort mode (default: digest_order).')
})

export const issuesListResponseResultsItemDigestOrderMin = 0;
export const issuesListResponseResultsItemDigestOrderMax = 2147483647;

export const issuesListResponseResultsItemDigestedEventCountMin = -2147483648;
export const issuesListResponseResultsItemDigestedEventCountMax = 2147483647;

export const issuesListResponseResultsItemCalculatedTypeMax = 128;

export const issuesListResponseResultsItemCalculatedValueMax = 1024;

export const issuesListResponseResultsItemTransactionMax = 200;



export const IssuesListResponse = zod.object({
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.uuid(),
  "project": zod.number(),
  "digest_order": zod.number().min(issuesListResponseResultsItemDigestOrderMin).max(issuesListResponseResultsItemDigestOrderMax),
  "last_seen": zod.iso.datetime({}),
  "first_seen": zod.iso.datetime({}),
  "digested_event_count": zod.number().min(issuesListResponseResultsItemDigestedEventCountMin).max(issuesListResponseResultsItemDigestedEventCountMax),
  "stored_event_count": zod.number(),
  "calculated_type": zod.string().max(issuesListResponseResultsItemCalculatedTypeMax).optional(),
  "calculated_value": zod.string().max(issuesListResponseResultsItemCalculatedValueMax).optional(),
  "transaction": zod.string().max(issuesListResponseResultsItemTransactionMax).optional(),
  "is_resolved": zod.boolean().optional(),
  "is_resolved_by_next_release": zod.boolean().optional(),
  "is_muted": zod.boolean().optional()
}))
})


/**
 * LIST requires: ?project=<uuid>
Optional: ?order=asc|desc        (default: desc)
LIST ordered by last_seen
RETRIEVE is a pure PK lookup (soft-deletes implied)
 */
export const IssuesRetrieveParams = zod.object({
  "id": zod.uuid().describe('A UUID string identifying this issue.')
})

export const issuesRetrieveResponseDigestOrderMin = 0;
export const issuesRetrieveResponseDigestOrderMax = 2147483647;

export const issuesRetrieveResponseDigestedEventCountMin = -2147483648;
export const issuesRetrieveResponseDigestedEventCountMax = 2147483647;

export const issuesRetrieveResponseCalculatedTypeMax = 128;

export const issuesRetrieveResponseCalculatedValueMax = 1024;

export const issuesRetrieveResponseTransactionMax = 200;



export const IssuesRetrieveResponse = zod.object({
  "id": zod.uuid(),
  "project": zod.number(),
  "digest_order": zod.number().min(issuesRetrieveResponseDigestOrderMin).max(issuesRetrieveResponseDigestOrderMax),
  "last_seen": zod.iso.datetime({}),
  "first_seen": zod.iso.datetime({}),
  "digested_event_count": zod.number().min(issuesRetrieveResponseDigestedEventCountMin).max(issuesRetrieveResponseDigestedEventCountMax),
  "stored_event_count": zod.number(),
  "calculated_type": zod.string().max(issuesRetrieveResponseCalculatedTypeMax).optional(),
  "calculated_value": zod.string().max(issuesRetrieveResponseCalculatedValueMax).optional(),
  "transaction": zod.string().max(issuesRetrieveResponseTransactionMax).optional(),
  "is_resolved": zod.boolean().optional(),
  "is_resolved_by_next_release": zod.boolean().optional(),
  "is_muted": zod.boolean().optional()
})


/**
 * /api/canonical/0/projects/
GET /projects/           → list ordered by name ASC, hides soft-deleted, optional ?team=<uuid> filter
GET /projects/{pk}/      → detail (pure PK)
POST /projects/          → create {team, name, visibility?}
PATCH /projects/{pk}/    → minimal updates
DELETE                   → 405
 */
export const ProjectsListQueryParams = zod.object({
  "cursor": zod.string().optional().describe('The pagination cursor value.'),
  "team": zod.uuid().optional().describe('Optional filter by team UUID.')
})

export const projectsListResponseResultsItemNameMax = 255;

export const projectsListResponseResultsItemSlugMax = 50;


export const projectsListResponseResultsItemSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const projectsListResponseResultsItemRetentionMaxEventCountMin = 0;
export const projectsListResponseResultsItemRetentionMaxEventCountMax = 2147483647;



export const ProjectsListResponse = zod.object({
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.number(),
  "team": zod.uuid().nullish(),
  "name": zod.string().max(projectsListResponseResultsItemNameMax),
  "slug": zod.string().max(projectsListResponseResultsItemSlugMax).regex(projectsListResponseResultsItemSlugRegExp),
  "dsn": zod.string(),
  "digested_event_count": zod.number(),
  "stored_event_count": zod.number(),
  "alert_on_new_issue": zod.boolean().optional(),
  "alert_on_regression": zod.boolean().optional(),
  "alert_on_unmute": zod.boolean().optional(),
  "visibility": zod.enum(['joinable', 'discoverable', 'team_members']).describe('\* `joinable` - joinable\n\* `discoverable` - discoverable\n\* `team_members` - team_members'),
  "retention_max_event_count": zod.number().min(projectsListResponseResultsItemRetentionMaxEventCountMin).max(projectsListResponseResultsItemRetentionMaxEventCountMax).optional()
}))
})


/**
 * /api/canonical/0/projects/
GET /projects/           → list ordered by name ASC, hides soft-deleted, optional ?team=<uuid> filter
GET /projects/{pk}/      → detail (pure PK)
POST /projects/          → create {team, name, visibility?}
PATCH /projects/{pk}/    → minimal updates
DELETE                   → 405
 */
export const projectsCreateBodyNameMax = 255;

export const projectsCreateBodyRetentionMaxEventCountMin = 0;
export const projectsCreateBodyRetentionMaxEventCountMax = 2147483647;



export const ProjectsCreateBody = zod.object({
  "team": zod.uuid(),
  "name": zod.string().max(projectsCreateBodyNameMax),
  "visibility": zod.enum(['joinable', 'discoverable', 'team_members']).optional().describe('\* `joinable` - joinable\n\* `discoverable` - discoverable\n\* `team_members` - team_members'),
  "alert_on_new_issue": zod.boolean().optional(),
  "alert_on_regression": zod.boolean().optional(),
  "alert_on_unmute": zod.boolean().optional(),
  "retention_max_event_count": zod.number().min(projectsCreateBodyRetentionMaxEventCountMin).max(projectsCreateBodyRetentionMaxEventCountMax).optional()
})


/**
 * /api/canonical/0/projects/
GET /projects/           → list ordered by name ASC, hides soft-deleted, optional ?team=<uuid> filter
GET /projects/{pk}/      → detail (pure PK)
POST /projects/          → create {team, name, visibility?}
PATCH /projects/{pk}/    → minimal updates
DELETE                   → 405
 */
export const ProjectsRetrieveParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this project.')
})

export const projectsRetrieveResponseNameMax = 255;

export const projectsRetrieveResponseSlugMax = 50;


export const projectsRetrieveResponseSlugRegExp = new RegExp('^[-a-zA-Z0-9_]+$');
export const projectsRetrieveResponseRetentionMaxEventCountMin = 0;
export const projectsRetrieveResponseRetentionMaxEventCountMax = 2147483647;



export const ProjectsRetrieveResponse = zod.object({
  "id": zod.number(),
  "team": zod.uuid().nullish(),
  "name": zod.string().max(projectsRetrieveResponseNameMax),
  "slug": zod.string().max(projectsRetrieveResponseSlugMax).regex(projectsRetrieveResponseSlugRegExp),
  "dsn": zod.string(),
  "digested_event_count": zod.number(),
  "stored_event_count": zod.number(),
  "alert_on_new_issue": zod.boolean().optional(),
  "alert_on_regression": zod.boolean().optional(),
  "alert_on_unmute": zod.boolean().optional(),
  "visibility": zod.enum(['joinable', 'discoverable', 'team_members']).describe('\* `joinable` - joinable\n\* `discoverable` - discoverable\n\* `team_members` - team_members'),
  "retention_max_event_count": zod.number().min(projectsRetrieveResponseRetentionMaxEventCountMin).max(projectsRetrieveResponseRetentionMaxEventCountMax).optional()
})


/**
 * /api/canonical/0/projects/
GET /projects/           → list ordered by name ASC, hides soft-deleted, optional ?team=<uuid> filter
GET /projects/{pk}/      → detail (pure PK)
POST /projects/          → create {team, name, visibility?}
PATCH /projects/{pk}/    → minimal updates
DELETE                   → 405
 */
export const ProjectsPartialUpdateParams = zod.object({
  "id": zod.number().describe('A unique integer value identifying this project.')
})

export const projectsPartialUpdateBodyNameMax = 255;

export const projectsPartialUpdateBodyRetentionMaxEventCountMin = 0;
export const projectsPartialUpdateBodyRetentionMaxEventCountMax = 2147483647;



export const ProjectsPartialUpdateBody = zod.object({
  "team": zod.uuid().optional(),
  "name": zod.string().max(projectsPartialUpdateBodyNameMax).optional(),
  "visibility": zod.enum(['joinable', 'discoverable', 'team_members']).optional().describe('\* `joinable` - joinable\n\* `discoverable` - discoverable\n\* `team_members` - team_members'),
  "alert_on_new_issue": zod.boolean().optional(),
  "alert_on_regression": zod.boolean().optional(),
  "alert_on_unmute": zod.boolean().optional(),
  "retention_max_event_count": zod.number().min(projectsPartialUpdateBodyRetentionMaxEventCountMin).max(projectsPartialUpdateBodyRetentionMaxEventCountMax).optional()
})

export const projectsPartialUpdateResponseNameMax = 255;

export const projectsPartialUpdateResponseRetentionMaxEventCountMin = 0;
export const projectsPartialUpdateResponseRetentionMaxEventCountMax = 2147483647;



export const ProjectsPartialUpdateResponse = zod.object({
  "id": zod.uuid(),
  "team": zod.uuid(),
  "name": zod.string().max(projectsPartialUpdateResponseNameMax),
  "visibility": zod.enum(['joinable', 'discoverable', 'team_members']).optional().describe('\* `joinable` - joinable\n\* `discoverable` - discoverable\n\* `team_members` - team_members'),
  "alert_on_new_issue": zod.boolean().optional(),
  "alert_on_regression": zod.boolean().optional(),
  "alert_on_unmute": zod.boolean().optional(),
  "retention_max_event_count": zod.number().min(projectsPartialUpdateResponseRetentionMaxEventCountMin).max(projectsPartialUpdateResponseRetentionMaxEventCountMax).optional()
})


/**
 * LIST requires: ?project=<id>
Ordered by sort_epoch.
CREATE allowed. DELETE potential TODO.
 */
export const ReleasesListQueryParams = zod.object({
  "cursor": zod.string().optional().describe('The pagination cursor value.'),
  "project": zod.number().describe('Filter releases by project id (required).')
})

export const releasesListResponseResultsItemVersionMax = 250;



export const ReleasesListResponse = zod.object({
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.uuid(),
  "project": zod.number(),
  "version": zod.string().max(releasesListResponseResultsItemVersionMax),
  "date_released": zod.iso.datetime({}).optional()
}))
})


/**
 * LIST requires: ?project=<id>
Ordered by sort_epoch.
CREATE allowed. DELETE potential TODO.
 */
export const ReleasesCreateBody = zod.object({
  "project": zod.number(),
  "version": zod.string(),
  "timestamp": zod.iso.datetime({}).optional()
})


/**
 * LIST requires: ?project=<id>
Ordered by sort_epoch.
CREATE allowed. DELETE potential TODO.
 */
export const ReleasesRetrieveParams = zod.object({
  "id": zod.uuid().describe('A UUID string identifying this release.')
})

export const releasesRetrieveResponseVersionMax = 250;



export const ReleasesRetrieveResponse = zod.object({
  "id": zod.uuid(),
  "project": zod.number(),
  "version": zod.string().max(releasesRetrieveResponseVersionMax),
  "date_released": zod.iso.datetime({}).optional(),
  "semver": zod.string(),
  "is_semver": zod.boolean(),
  "sort_epoch": zod.number()
})


/**
 * /api/canonical/0/teams/
GET /teams/           → list ordered by name ASC
GET /teams/{pk}/      → detail (pure PK)
POST /teams/          → create {name, visibility?}
PATCH /teams/{pk}/    → minimal updates
DELETE                → 405
 */
export const TeamsListQueryParams = zod.object({
  "cursor": zod.string().optional().describe('The pagination cursor value.')
})

export const teamsListResponseResultsItemNameMax = 255;



export const TeamsListResponse = zod.object({
  "next": zod.url().nullish(),
  "previous": zod.url().nullish(),
  "results": zod.array(zod.object({
  "id": zod.uuid(),
  "name": zod.string().max(teamsListResponseResultsItemNameMax),
  "visibility": zod.enum(['joinable', 'discoverable', 'hidden']).describe('\* `joinable` - joinable\n\* `discoverable` - discoverable\n\* `hidden` - hidden')
}))
})


/**
 * /api/canonical/0/teams/
GET /teams/           → list ordered by name ASC
GET /teams/{pk}/      → detail (pure PK)
POST /teams/          → create {name, visibility?}
PATCH /teams/{pk}/    → minimal updates
DELETE                → 405
 */
export const teamsCreateBodyNameMax = 255;



export const TeamsCreateBody = zod.object({
  "name": zod.string().max(teamsCreateBodyNameMax),
  "visibility": zod.enum(['joinable', 'discoverable', 'hidden']).optional().describe('\* `joinable` - joinable\n\* `discoverable` - discoverable\n\* `hidden` - hidden')
})


/**
 * /api/canonical/0/teams/
GET /teams/           → list ordered by name ASC
GET /teams/{pk}/      → detail (pure PK)
POST /teams/          → create {name, visibility?}
PATCH /teams/{pk}/    → minimal updates
DELETE                → 405
 */
export const TeamsRetrieveParams = zod.object({
  "id": zod.uuid().describe('A UUID string identifying this team.')
})

export const teamsRetrieveResponseNameMax = 255;



export const TeamsRetrieveResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string().max(teamsRetrieveResponseNameMax),
  "visibility": zod.enum(['joinable', 'discoverable', 'hidden']).describe('\* `joinable` - joinable\n\* `discoverable` - discoverable\n\* `hidden` - hidden')
})


/**
 * /api/canonical/0/teams/
GET /teams/           → list ordered by name ASC
GET /teams/{pk}/      → detail (pure PK)
POST /teams/          → create {name, visibility?}
PATCH /teams/{pk}/    → minimal updates
DELETE                → 405
 */
export const TeamsPartialUpdateParams = zod.object({
  "id": zod.uuid().describe('A UUID string identifying this team.')
})

export const teamsPartialUpdateBodyNameMax = 255;



export const TeamsPartialUpdateBody = zod.object({
  "name": zod.string().max(teamsPartialUpdateBodyNameMax).optional(),
  "visibility": zod.enum(['joinable', 'discoverable', 'hidden']).optional().describe('\* `joinable` - joinable\n\* `discoverable` - discoverable\n\* `hidden` - hidden')
})

export const teamsPartialUpdateResponseNameMax = 255;



export const TeamsPartialUpdateResponse = zod.object({
  "id": zod.uuid(),
  "name": zod.string().max(teamsPartialUpdateResponseNameMax),
  "visibility": zod.enum(['joinable', 'discoverable', 'hidden']).optional().describe('\* `joinable` - joinable\n\* `discoverable` - discoverable\n\* `hidden` - hidden')
})
