/**
 * Generated by orval v8.5.3 🍺
 * Do not edit manually.
 * Flavortown API
 * You need an API key to use this! Go to your [account settings](https://flavortown.hackclub.com/kitchen?settings=1) to get one.
 * OpenAPI spec version: v1
 */
import * as zod from "zod";

/**
 * Fetch a list of projects. Ratelimit: 5 reqs/min, 20 reqs/min if searching.
 * @summary List projects
 */
export const listProjectsQueryLimitMax = 100;

export const ListProjectsQueryParams = zod.object({
  page: zod.number().nullish().describe("Page number for pagination"),
  limit: zod
    .number()
    .max(listProjectsQueryLimitMax)
    .nullish()
    .describe("Number of results per page (max 100)"),
  query: zod
    .string()
    .nullish()
    .describe("Search projects by title or description"),
});

export const ListProjectsResponse = zod.object({
  projects: zod
    .array(
      zod.object({
        id: zod.number().nullish(),
        title: zod.string().nullish(),
        description: zod.string().nullish(),
        repo_url: zod.string().nullish(),
        demo_url: zod.string().nullish(),
        readme_url: zod.string().nullish(),
        ai_declaration: zod.string().nullish(),
        ship_status: zod.string().nullish(),
        devlog_ids: zod.array(zod.number()).nullish(),
        banner_url: zod.string().nullish(),
        created_at: zod.iso.datetime({}).nullish(),
        updated_at: zod.iso.datetime({}).nullish(),
      }),
    )
    .nullish(),
  pagination: zod
    .object({
      current_page: zod.number().nullish(),
      total_pages: zod.number().nullish(),
      total_count: zod.number().nullish(),
      next_page: zod.number().nullish(),
    })
    .nullish(),
});

/**
 * Fetch a specific project by ID. Ratelimit: 30 reqs/min.
 * @summary Get a project
 */
export const GetProjectParams = zod.object({
  id: zod.number(),
});

export const GetProjectResponse = zod.object({
  id: zod.number().nullish(),
  title: zod.string().nullish(),
  description: zod.string().nullish(),
  repo_url: zod.string().nullish(),
  demo_url: zod.string().nullish(),
  readme_url: zod.string().nullish(),
  ai_declaration: zod.string().nullish(),
  ship_status: zod.string().nullish(),
  devlog_ids: zod.array(zod.number()).nullish(),
  banner_url: zod.string().nullish(),
  created_at: zod.iso.datetime({}).nullish(),
  updated_at: zod.iso.datetime({}).nullish(),
});

/**
 * Update an existing project.
 * @summary Update a project
 */
export const UpdateProjectParams = zod.object({
  id: zod.number(),
});

export const UpdateProjectResponse = zod.object({
  id: zod.number().nullish(),
  title: zod.string().nullish(),
  description: zod.string().nullish(),
  repo_url: zod.string().nullish(),
  demo_url: zod.string().nullish(),
  readme_url: zod.string().nullish(),
  ai_declaration: zod.string().nullish(),
  ship_status: zod.string().nullish(),
  devlog_ids: zod.array(zod.number()).nullish(),
  banner_url: zod.string().nullish(),
  created_at: zod.iso.datetime({}).nullish(),
  updated_at: zod.iso.datetime({}).nullish(),
});

/**
 * Fetch all devlogs for a specific project.
 * @summary List project devlogs
 */
export const ListProjectDevlogsParams = zod.object({
  project_id: zod.number(),
});

export const listProjectDevlogsQueryLimitMax = 100;

export const ListProjectDevlogsQueryParams = zod.object({
  page: zod.number().nullish().describe("Page number for pagination"),
  limit: zod
    .number()
    .max(listProjectDevlogsQueryLimitMax)
    .nullish()
    .describe("Number of results per page (max 100)"),
});

export const ListProjectDevlogsResponse = zod.object({
  devlogs: zod
    .array(
      zod.object({
        id: zod.number().nullish(),
        body: zod.string().nullish(),
        comments_count: zod.number().nullish(),
        duration_seconds: zod.number().nullish(),
        likes_count: zod.number().nullish(),
        scrapbook_url: zod.string().nullish(),
        created_at: zod.iso.datetime({}).nullish(),
        updated_at: zod.iso.datetime({}).nullish(),
        media: zod
          .array(
            zod.object({
              url: zod.string().nullish(),
              content_type: zod.string().nullish(),
            }),
          )
          .nullish(),
        comments: zod
          .array(
            zod.object({
              id: zod.number().nullish(),
              author: zod
                .object({
                  id: zod.number().nullish(),
                  display_name: zod.string().nullish(),
                  avatar: zod.string().nullish(),
                })
                .nullish(),
              body: zod.string().nullish(),
              created_at: zod.iso.datetime({}).nullish(),
              updated_at: zod.iso.datetime({}).nullish(),
            }),
          )
          .nullish(),
      }),
    )
    .nullish(),
  pagination: zod
    .object({
      current_page: zod.number().nullish(),
      total_pages: zod.number().nullish(),
      total_count: zod.number().nullish(),
      next_page: zod.number().nullish(),
    })
    .nullish(),
});

/**
 * Fetch all devlogs across all projects.
 * @summary List devlogs
 */
export const listDevlogsQueryLimitMax = 100;

export const ListDevlogsQueryParams = zod.object({
  page: zod.number().nullish().describe("Page number for pagination"),
  limit: zod
    .number()
    .max(listDevlogsQueryLimitMax)
    .nullish()
    .describe("Number of results per page (max 100)"),
});

export const ListDevlogsResponse = zod.object({
  devlogs: zod
    .array(
      zod.object({
        id: zod.number().nullish(),
        body: zod.string().nullish(),
        comments_count: zod.number().nullish(),
        duration_seconds: zod.number().nullish(),
        likes_count: zod.number().nullish(),
        scrapbook_url: zod.string().nullish(),
        created_at: zod.iso.datetime({}).nullish(),
        updated_at: zod.iso.datetime({}).nullish(),
        media: zod
          .array(
            zod.object({
              url: zod.string().nullish(),
              content_type: zod.string().nullish(),
            }),
          )
          .nullish(),
        comments: zod
          .array(
            zod.object({
              id: zod.number().nullish(),
              author: zod
                .object({
                  id: zod.number().nullish(),
                  display_name: zod.string().nullish(),
                  avatar: zod.string().nullish(),
                })
                .nullish(),
              body: zod.string().nullish(),
              created_at: zod.iso.datetime({}).nullish(),
              updated_at: zod.iso.datetime({}).nullish(),
            }),
          )
          .nullish(),
      }),
    )
    .nullish(),
  pagination: zod
    .object({
      current_page: zod.number().nullish(),
      total_pages: zod.number().nullish(),
      total_count: zod.number().nullish(),
      next_page: zod.number().nullish(),
    })
    .nullish(),
});

/**
 * Fetch a devlog by ID.
 * @summary Get a devlog
 */
export const GetDevlogParams = zod.object({
  id: zod.number(),
});

export const GetDevlogResponse = zod.object({
  id: zod.number().nullish(),
  body: zod.string().nullish(),
  comments_count: zod.number().nullish(),
  duration_seconds: zod.number().nullish(),
  likes_count: zod.number().nullish(),
  scrapbook_url: zod.string().nullish(),
  created_at: zod.iso.datetime({}).nullish(),
  updated_at: zod.iso.datetime({}).nullish(),
  media: zod
    .array(
      zod.object({
        url: zod.string().nullish(),
        content_type: zod.string().nullish(),
      }),
    )
    .nullish(),
  comments: zod
    .array(
      zod.object({
        id: zod.number().nullish(),
        author: zod
          .object({
            id: zod.number().nullish(),
            display_name: zod.string().nullish(),
            avatar: zod.string().nullish(),
          })
          .nullish(),
        body: zod.string().nullish(),
        created_at: zod.iso.datetime({}).nullish(),
        updated_at: zod.iso.datetime({}).nullish(),
      }),
    )
    .nullish(),
});

/**
 * Fetch a list of store items. Ratelimit: 5 reqs/min.
 * @summary List store items
 */
export const ListStoreItemsResponseItem = zod.object({
  id: zod.number().nullish(),
  name: zod.string().nullish(),
  description: zod.string().nullish(),
  old_prices: zod.array(zod.unknown()).nullish(),
  limited: zod.boolean().nullish(),
  stock: zod.number().nullish(),
  type: zod.string().nullish(),
  show_in_carousel: zod.boolean().nullish(),
  accessory_tag: zod.string().nullish(),
  agh_contents: zod.string().nullish(),
  attached_shop_item_ids: zod.array(zod.unknown()).nullish(),
  buyable_by_self: zod.boolean().nullish(),
  long_description: zod.string().nullish(),
  max_qty: zod.number().nullish(),
  one_per_person_ever: zod.boolean().nullish(),
  sale_percentage: zod.number().nullish(),
  image_url: zod.string().nullish(),
  enabled: zod
    .object({
      enabled_au: zod.boolean().nullish(),
      enabled_ca: zod.boolean().nullish(),
      enabled_eu: zod.boolean().nullish(),
      enabled_in: zod.boolean().nullish(),
      enabled_uk: zod.boolean().nullish(),
      enabled_us: zod.boolean().nullish(),
      enabled_xx: zod.boolean().nullish(),
    })
    .nullish(),
  ticket_cost: zod
    .object({
      base_cost: zod.number().nullish(),
      au: zod.number().nullish(),
      ca: zod.number().nullish(),
      eu: zod.number().nullish(),
      in: zod.number().nullish(),
      uk: zod.number().nullish(),
      us: zod.number().nullish(),
      xx: zod.number().nullish(),
    })
    .nullish(),
});
export const ListStoreItemsResponse = zod.array(ListStoreItemsResponseItem);

/**
 * Fetch a specific store item by ID. Ratelimit: 30 reqs/min.
 * @summary Get a store item
 */
export const GetStoreItemParams = zod.object({
  id: zod.number(),
});

export const GetStoreItemResponse = zod.object({
  id: zod.number().nullish(),
  name: zod.string().nullish(),
  description: zod.string().nullish(),
  old_prices: zod.array(zod.unknown()).nullish(),
  limited: zod.boolean().nullish(),
  stock: zod.number().nullish(),
  type: zod.string().nullish(),
  show_in_carousel: zod.boolean().nullish(),
  accessory_tag: zod.string().nullish(),
  agh_contents: zod.string().nullish(),
  attached_shop_item_ids: zod.array(zod.unknown()).nullish(),
  buyable_by_self: zod.boolean().nullish(),
  long_description: zod.string().nullish(),
  max_qty: zod.number().nullish(),
  one_per_person_ever: zod.boolean().nullish(),
  sale_percentage: zod.number().nullish(),
  image_url: zod.string().nullish(),
  enabled: zod
    .object({
      enabled_au: zod.boolean().nullish(),
      enabled_ca: zod.boolean().nullish(),
      enabled_eu: zod.boolean().nullish(),
      enabled_in: zod.boolean().nullish(),
      enabled_uk: zod.boolean().nullish(),
      enabled_us: zod.boolean().nullish(),
      enabled_xx: zod.boolean().nullish(),
    })
    .nullish(),
  ticket_cost: zod
    .object({
      base_cost: zod.number().nullish(),
      au: zod.number().nullish(),
      ca: zod.number().nullish(),
      eu: zod.number().nullish(),
      in: zod.number().nullish(),
      uk: zod.number().nullish(),
      us: zod.number().nullish(),
      xx: zod.number().nullish(),
    })
    .nullish(),
});

/**
 * Fetch a list of users. Ratelimit: 5 reqs/min.
 * @summary List users
 */
export const listUsersQueryLimitMax = 100;

export const ListUsersQueryParams = zod.object({
  page: zod.number().nullish().describe("Page number for pagination"),
  limit: zod
    .number()
    .max(listUsersQueryLimitMax)
    .nullish()
    .describe("Number of results per page (max 100)"),
  query: zod
    .string()
    .nullish()
    .describe("Search users by display name or slack ID"),
});

export const ListUsersResponse = zod.object({
  users: zod
    .array(
      zod.object({
        id: zod.number().nullish(),
        slack_id: zod.string().nullish(),
        display_name: zod.string().nullish(),
        avatar: zod.string().nullish(),
        project_ids: zod.array(zod.number()).nullish(),
        cookies: zod.number().nullish(),
      }),
    )
    .nullish(),
  pagination: zod
    .object({
      current_page: zod.number().nullish(),
      total_pages: zod.number().nullish(),
      total_count: zod.number().nullish(),
      next_page: zod.number().nullish(),
    })
    .nullish(),
});

/**
 * Fetch a specific user by ID. Use "me" as the ID to fetch the authenticated user.
 * @summary Get a user
 */
export const GetUserParams = zod.object({
  id: zod.string().describe('User ID or \"me\" for the authenticated user'),
});

export const GetUserResponse = zod
  .object({
    id: zod.number().nullish(),
    slack_id: zod.string().nullish(),
    display_name: zod.string().nullish(),
    avatar: zod.string().nullish(),
    project_ids: zod.array(zod.number()).nullish(),
    cookies: zod.number().nullish(),
  })
  .and(
    zod.object({
      vote_count: zod.number().nullish(),
      like_count: zod.number().nullish(),
      devlog_seconds_total: zod.number().nullish(),
      devlog_seconds_today: zod.number().nullish(),
      achievements: zod
        .array(
          zod.object({
            slug: zod.string().nullish(),
            name: zod.string().nullish(),
            description: zod.string().nullish(),
          }),
        )
        .nullish(),
    }),
  );
