services:
  logpheus:
    build:
      context: .
      dockerfile: MP.Dockerfile
    env_file: .env
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: always
    ports:
      - 53814:3000
    volumes:
      - cache:/usr/src/app/cache
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/healthcheck"]
      interval: 2s
      timeout: 2s
      retries: 5
      start_period: 4s

volumes:
  cache:
