/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * HCBScan API
 * HCBScan is the first public explorer for HCB organizations, users, and transactions and it indexes and aggregates data from HCB, providing unique insights like user net worth, cross-org activity feeds, leaderboards, searching, and more. This is the public API so you can integrate with it.

## Rate Limits

- 60 requests per minute (by IP)
- Rate limit headers are included on every response: `X-RateLimit-Limit`, `X-RateLimit-Remaining`, `X-RateLimit-Reset`

## Response Format

All responses use a consistent envelope:

```json
{
  "ok": true,
  "data": { ... },
  "meta": { "page": 1, "per_page": 50, "total": 1234, "has_more": true }
}
```

Errors return:

```json
{
  "ok": false,
  "error": { "code": "NOT_FOUND", "message": "Organization not found" }
}
```
 * OpenAPI spec version: 1.0.0
 */
import * as zod from 'zod';

/**
 * Returns a paginated list of all indexed HCB organizations. Supports sorting and filtering by category.
 * @summary List organizations
 */
export const listOrgsQueryPageDefault = 1;

export const listOrgsQueryPerPageDefault = 50;
export const listOrgsQueryPerPageMax = 100;

export const listOrgsQuerySortDefault = `balance`;
export const listOrgsQueryOrderDefault = `desc`;

export const ListOrgsQueryParams = zod.object({
  "page": zod.number().min(1).default(listOrgsQueryPageDefault).describe('Page number'),
  "per_page": zod.number().min(1).max(listOrgsQueryPerPageMax).default(listOrgsQueryPerPageDefault).describe('Results per page'),
  "sort": zod.enum(['balance', 'name', 'added']).default(listOrgsQuerySortDefault).describe('Sort field'),
  "order": zod.enum(['asc', 'desc']).default(listOrgsQueryOrderDefault).describe('Sort order'),
  "category": zod.string().optional().describe('Filter by category')
})

export const ListOrgsResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "slug": zod.string().optional(),
  "category": zod.string().nullish(),
  "balance_cents": zod.number().optional(),
  "added": zod.iso.datetime({}).optional(),
  "frozen_at": zod.iso.datetime({}).nullish()
})).optional(),
  "meta": zod.object({
  "page": zod.number().optional(),
  "per_page": zod.number().optional(),
  "total": zod.number().optional(),
  "has_more": zod.boolean().optional()
}).optional()
}))


/**
 * Returns details for a single organization by its ID.
 * @summary Get organization
 */
export const GetOrgParams = zod.object({
  "id": zod.string().describe('Organization ID')
})

export const GetOrgResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "slug": zod.string().optional(),
  "category": zod.string().nullish(),
  "balance_cents": zod.number().optional(),
  "added": zod.iso.datetime({}).optional(),
  "frozen_at": zod.iso.datetime({}).nullish()
}).optional()
}))


/**
 * Returns a paginated activity feed for a specific organization.
 * @summary Get organization activities
 */
export const GetOrgActivitiesParams = zod.object({
  "id": zod.string().describe('Organization ID')
})

export const getOrgActivitiesQueryPageDefault = 1;
export const getOrgActivitiesQueryPerPageDefault = 50;
export const getOrgActivitiesQueryPerPageMax = 100;



export const GetOrgActivitiesQueryParams = zod.object({
  "page": zod.number().default(getOrgActivitiesQueryPageDefault),
  "per_page": zod.number().max(getOrgActivitiesQueryPerPageMax).default(getOrgActivitiesQueryPerPageDefault)
})

export const GetOrgActivitiesResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "key": zod.string().optional(),
  "created_at": zod.iso.datetime({}).optional(),
  "user": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "avatar": zod.string().nullish()
}).nullish(),
  "organization": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "logo": zod.string().nullish()
}).nullish()
})).optional(),
  "meta": zod.object({
  "page": zod.number().optional(),
  "per_page": zod.number().optional(),
  "total": zod.number().optional(),
  "has_more": zod.boolean().optional()
}).optional()
}))


/**
 * Returns all users associated with a specific organization.
 * @summary Get organization users
 */
export const GetOrgUsersParams = zod.object({
  "id": zod.string().describe('Organization ID')
})

export const GetOrgUsersResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "avatar": zod.string().nullish()
})).optional()
}))


/**
 * Returns a user's profile including their organizations with balances, net worth, and activity count.
 * @summary Get user profile
 */
export const GetUserParams = zod.object({
  "id": zod.string().describe('User ID')
})

export const GetUserResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "avatar": zod.string().nullish(),
  "organizations": zod.array(zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "logo": zod.string().nullish(),
  "balance_cents": zod.number().nullish()
})).optional(),
  "net_worth_cents": zod.number().optional(),
  "activity_count": zod.number().optional()
}).optional()
}))


/**
 * Returns a paginated activity feed for a specific user.
 * @summary Get user activities
 */
export const GetUserActivitiesParams = zod.object({
  "id": zod.string().describe('User ID')
})

export const getUserActivitiesQueryPageDefault = 1;
export const getUserActivitiesQueryPerPageDefault = 50;
export const getUserActivitiesQueryPerPageMax = 100;



export const GetUserActivitiesQueryParams = zod.object({
  "page": zod.number().default(getUserActivitiesQueryPageDefault),
  "per_page": zod.number().max(getUserActivitiesQueryPerPageMax).default(getUserActivitiesQueryPerPageDefault)
})

export const GetUserActivitiesResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "key": zod.string().optional(),
  "created_at": zod.iso.datetime({}).optional(),
  "user": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "avatar": zod.string().nullish()
}).nullish(),
  "organization": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "logo": zod.string().nullish()
}).nullish()
})).optional(),
  "meta": zod.object({
  "page": zod.number().optional(),
  "per_page": zod.number().optional(),
  "total": zod.number().optional(),
  "has_more": zod.boolean().optional()
}).optional()
}))


/**
 * Returns a paginated global activity feed. Supports filtering by organization, user, activity type, and date range.
 * @summary List activities
 */
export const listActivitiesQueryPageDefault = 1;
export const listActivitiesQueryPerPageDefault = 50;
export const listActivitiesQueryPerPageMax = 100;



export const ListActivitiesQueryParams = zod.object({
  "page": zod.number().default(listActivitiesQueryPageDefault),
  "per_page": zod.number().max(listActivitiesQueryPerPageMax).default(listActivitiesQueryPerPageDefault),
  "org_id": zod.string().optional().describe('Filter by organization ID'),
  "user_id": zod.string().optional().describe('Filter by user ID'),
  "key": zod.string().optional().describe('Filter by activity type key'),
  "after": zod.iso.datetime({}).optional().describe('Only activities after this timestamp'),
  "before": zod.iso.datetime({}).optional().describe('Only activities before this timestamp')
})

export const ListActivitiesResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.array(zod.object({
  "id": zod.string().optional(),
  "key": zod.string().optional(),
  "created_at": zod.iso.datetime({}).optional(),
  "user": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "avatar": zod.string().nullish()
}).nullish(),
  "organization": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "logo": zod.string().nullish()
}).nullish()
})).optional(),
  "meta": zod.object({
  "page": zod.number().optional(),
  "per_page": zod.number().optional(),
  "total": zod.number().optional(),
  "has_more": zod.boolean().optional()
}).optional()
}))


/**
 * Full-text search across organizations, users, and activities.
 * @summary Search
 */
export const searchQueryScopeDefault = `all`;
export const searchQueryLimitDefault = 15;
export const searchQueryLimitMax = 50;



export const SearchQueryParams = zod.object({
  "q": zod.string().describe('Search query'),
  "scope": zod.enum(['all', 'orgs', 'users', 'activities']).default(searchQueryScopeDefault).describe('Limit search to a specific entity type'),
  "limit": zod.number().max(searchQueryLimitMax).default(searchQueryLimitDefault).describe('Max results per entity type')
})

export const SearchResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.object({
  "orgs": zod.array(zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "slug": zod.string().optional(),
  "category": zod.string().nullish(),
  "balance_cents": zod.number().optional()
})).optional(),
  "users": zod.array(zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional(),
  "avatar": zod.string().nullish()
})).optional(),
  "activities": zod.array(zod.object({
  "id": zod.string().optional(),
  "key": zod.string().optional(),
  "created_at": zod.iso.datetime({}).optional(),
  "user": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional()
}).nullish(),
  "organization": zod.object({
  "id": zod.string().optional(),
  "name": zod.string().optional()
}).nullish()
})).optional()
}).optional()
}))


/**
 * Returns high-level aggregate statistics: total organizations, total balance, and 7-day activity volume.
 * @summary Get overview stats
 */
export const GetStatsResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.object({
  "total_organizations": zod.number().optional(),
  "total_balance_cents": zod.number().optional(),
  "activity_volume_7d": zod.number().optional(),
  "activity_volume_previous_7d": zod.number().optional()
}).optional()
}))


/**
 * Returns ranked leaderboards. Supports balance rankings for orgs, and activity rankings for orgs and users over configurable time periods.
 * @summary Get leaderboard
 */
export const getLeaderboardQueryPeriodDefault = `7d`;
export const getLeaderboardQueryLimitDefault = 10;
export const getLeaderboardQueryLimitMax = 50;



export const GetLeaderboardQueryParams = zod.object({
  "type": zod.enum(['balance', 'active_orgs', 'active_users']).describe('Leaderboard type'),
  "period": zod.enum(['7d', '30d']).default(getLeaderboardQueryPeriodDefault).describe('Time period for activity leaderboards'),
  "limit": zod.number().min(1).max(getLeaderboardQueryLimitMax).default(getLeaderboardQueryLimitDefault).describe('Number of results')
})

export const GetLeaderboardResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.array(zod.object({
  "rank": zod.number().optional(),
  "id": zod.string().optional(),
  "name": zod.string().optional()
})).optional()
}))


/**
 * Returns the current API version and service health status.
 * @summary API status
 */
export const GetStatusResponse = zod.object({
  "ok": zod.boolean()
}).and(zod.object({
  "data": zod.object({
  "api_version": zod.string().optional(),
  "status": zod.string().optional(),
  "services": zod.record(zod.string(), zod.boolean()).optional()
}).optional()
}))
