/**
 * Generated by orval v8.5.1 🍺
 * Do not edit manually.
 * Stardance API
 * API for accessing Stardance hackclub project data. All endpoints are read-only and return cached results. When cached data is older than 12 hours, the requested resource is re-scraped synchronously while cascading refreshes run in the background.
 * OpenAPI spec version: 2.0.0
 */
import * as zod from "zod";

export namespace ZTypes {
  /**
   * Fetch a paginated list of all projects. Supports optional search query and limit.
   * @summary List projects (V1)
   */
  export const listProjectsV1QueryLimitMax = 100;

  export const ListProjectsV1QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listProjectsV1QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 20)"),
    query: zod
      .string()
      .optional()
      .describe("Search projects by title or description"),
  });

  export const ListProjectsV1Response = zod.object({
    projects: zod
      .array(
        zod.object({
          id: zod.number().describe("Project ID (from stardance.hackclub.com)"),
          title: zod.string(),
          description: zod.string().optional(),
          repo_url: zod.url().nullish(),
          demo_url: zod.url().nullish(),
          readme_url: zod.url().nullish(),
          ai_declaration: zod.string().nullish(),
          ship_status: zod.string().nullish(),
          devlog_ids: zod.array(zod.number()).optional(),
          banner_url: zod.url().nullish(),
          created_at: zod.iso.datetime({}).optional(),
          updated_at: zod.iso.datetime({}).optional(),
        }),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * @summary Get a project (V1)
   */
  export const GetProjectV1Params = zod.object({
    id: zod.number().describe("Project ID"),
  });

  export const GetProjectV1Response = zod.object({
    id: zod.number().describe("Project ID (from stardance.hackclub.com)"),
    title: zod.string(),
    description: zod.string().optional(),
    repo_url: zod.url().nullish(),
    demo_url: zod.url().nullish(),
    readme_url: zod.url().nullish(),
    ai_declaration: zod.string().nullish(),
    ship_status: zod.string().nullish(),
    devlog_ids: zod.array(zod.number()).optional(),
    banner_url: zod.url().nullish(),
    created_at: zod.iso.datetime({}).optional(),
    updated_at: zod.iso.datetime({}).optional(),
  });

  /**
   * Fetch a paginated list of devlogs belonging to a specific project.
   * @summary List devlogs for a project (V1)
   */
  export const ListProjectDevlogsV1Params = zod.object({
    id: zod.number().describe("Project ID"),
  });

  export const listProjectDevlogsV1QueryLimitMax = 100;

  export const ListProjectDevlogsV1QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listProjectDevlogsV1QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 20)"),
  });

  export const ListProjectDevlogsV1Response = zod.object({
    devlogs: zod
      .array(
        zod.object({
          id: zod.number().describe("Devlog ID (from stardance.hackclub.com)"),
          body: zod.string().describe("Devlog text content"),
          comments_count: zod
            .number()
            .optional()
            .describe("Total number of comments"),
          duration_seconds: zod
            .number()
            .optional()
            .describe("Duration in seconds"),
          likes_count: zod.number().optional(),
          scrapbook_url: zod.url().nullish(),
          media: zod
            .array(
              zod.object({
                url: zod.url().optional(),
                content_type: zod.string().optional(),
              }),
            )
            .optional()
            .describe("Media attachments (derived from image_urls)"),
          comments: zod
            .array(
              zod.object({
                id: zod.number().describe("Internal comment ID"),
                author: zod
                  .object({
                    id: zod.uuid().optional(),
                    display_name: zod.string().optional(),
                    avatar: zod.url().nullish(),
                  })
                  .nullish(),
                body: zod.string().describe("Comment body"),
                created_at: zod.iso.datetime({}).optional(),
                updated_at: zod.iso.datetime({}).optional(),
              }),
            )
            .optional(),
          created_at: zod.iso.datetime({}).optional(),
          updated_at: zod.iso.datetime({}).optional(),
        }),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * @summary Get a devlog scoped to a project (V1)
   */
  export const GetProjectDevlogV1Params = zod.object({
    id: zod.number().describe("Project ID"),
    devlog_id: zod.number().describe("Devlog ID"),
  });

  export const GetProjectDevlogV1Response = zod.object({
    id: zod.number().describe("Devlog ID (from stardance.hackclub.com)"),
    body: zod.string().describe("Devlog text content"),
    comments_count: zod
      .number()
      .optional()
      .describe("Total number of comments"),
    duration_seconds: zod.number().optional().describe("Duration in seconds"),
    likes_count: zod.number().optional(),
    scrapbook_url: zod.url().nullish(),
    media: zod
      .array(
        zod.object({
          url: zod.url().optional(),
          content_type: zod.string().optional(),
        }),
      )
      .optional()
      .describe("Media attachments (derived from image_urls)"),
    comments: zod
      .array(
        zod.object({
          id: zod.number().describe("Internal comment ID"),
          author: zod
            .object({
              id: zod.uuid().optional(),
              display_name: zod.string().optional(),
              avatar: zod.url().nullish(),
            })
            .nullish(),
          body: zod.string().describe("Comment body"),
          created_at: zod.iso.datetime({}).optional(),
          updated_at: zod.iso.datetime({}).optional(),
        }),
      )
      .optional(),
    created_at: zod.iso.datetime({}).optional(),
    updated_at: zod.iso.datetime({}).optional(),
  });

  /**
   * Fetch a paginated list of all devlogs across all projects.
   * @summary List all devlogs (V1)
   */
  export const listDevlogsV1QueryLimitMax = 100;

  export const ListDevlogsV1QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listDevlogsV1QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 20)"),
  });

  export const ListDevlogsV1Response = zod.object({
    devlogs: zod
      .array(
        zod.object({
          id: zod.number().describe("Devlog ID (from stardance.hackclub.com)"),
          body: zod.string().describe("Devlog text content"),
          comments_count: zod
            .number()
            .optional()
            .describe("Total number of comments"),
          duration_seconds: zod
            .number()
            .optional()
            .describe("Duration in seconds"),
          likes_count: zod.number().optional(),
          scrapbook_url: zod.url().nullish(),
          media: zod
            .array(
              zod.object({
                url: zod.url().optional(),
                content_type: zod.string().optional(),
              }),
            )
            .optional()
            .describe("Media attachments (derived from image_urls)"),
          comments: zod
            .array(
              zod.object({
                id: zod.number().describe("Internal comment ID"),
                author: zod
                  .object({
                    id: zod.uuid().optional(),
                    display_name: zod.string().optional(),
                    avatar: zod.url().nullish(),
                  })
                  .nullish(),
                body: zod.string().describe("Comment body"),
                created_at: zod.iso.datetime({}).optional(),
                updated_at: zod.iso.datetime({}).optional(),
              }),
            )
            .optional(),
          created_at: zod.iso.datetime({}).optional(),
          updated_at: zod.iso.datetime({}).optional(),
        }),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * @summary Get a devlog by ID (V1)
   */
  export const GetDevlogV1Params = zod.object({
    id: zod.number().describe("Devlog ID"),
  });

  export const GetDevlogV1Response = zod.object({
    id: zod.number().describe("Devlog ID (from stardance.hackclub.com)"),
    body: zod.string().describe("Devlog text content"),
    comments_count: zod
      .number()
      .optional()
      .describe("Total number of comments"),
    duration_seconds: zod.number().optional().describe("Duration in seconds"),
    likes_count: zod.number().optional(),
    scrapbook_url: zod.url().nullish(),
    media: zod
      .array(
        zod.object({
          url: zod.url().optional(),
          content_type: zod.string().optional(),
        }),
      )
      .optional()
      .describe("Media attachments (derived from image_urls)"),
    comments: zod
      .array(
        zod.object({
          id: zod.number().describe("Internal comment ID"),
          author: zod
            .object({
              id: zod.uuid().optional(),
              display_name: zod.string().optional(),
              avatar: zod.url().nullish(),
            })
            .nullish(),
          body: zod.string().describe("Comment body"),
          created_at: zod.iso.datetime({}).optional(),
          updated_at: zod.iso.datetime({}).optional(),
        }),
      )
      .optional(),
    created_at: zod.iso.datetime({}).optional(),
    updated_at: zod.iso.datetime({}).optional(),
  });

  /**
   * Fetch a paginated list of all users. Supports optional search query.
   * @summary List users (V1)
   */
  export const listUsersV1QueryLimitMax = 100;

  export const ListUsersV1QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listUsersV1QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 20)"),
    query: zod.string().optional().describe("Search users by username or bio"),
  });

  export const ListUsersV1Response = zod.object({
    users: zod
      .array(
        zod.object({
          id: zod.uuid().describe("Internal user ID"),
          slack_id: zod.string().nullish(),
          display_name: zod
            .string()
            .describe("Display name (same as username)"),
          avatar: zod.url().nullish().describe("Profile picture URL"),
          project_ids: zod.array(zod.number()).optional(),
          stardust: zod.number().nullish(),
        }),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * @summary Get a user profile (V1)
   */
  export const GetUserV1Params = zod.object({
    username: zod.string().describe('Username (with or without \"@\" prefix)'),
  });

  export const GetUserV1Response = zod.object({
    id: zod.uuid().describe("Internal user ID"),
    slack_id: zod.string().nullish(),
    display_name: zod.string().describe("Display name (same as username)"),
    avatar: zod.url().nullish().describe("Profile picture URL"),
    project_ids: zod.array(zod.number()).optional(),
    stardust: zod.number().nullish(),
  });

  /**
   * Fetch a paginated list of projects belonging to a specific user.
   * @summary List projects for a user (V1)
   */
  export const ListUserProjectsV1Params = zod.object({
    username: zod.string().describe('Username (with or without \"@\" prefix)'),
  });

  export const listUserProjectsV1QueryLimitMax = 100;

  export const ListUserProjectsV1QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listUserProjectsV1QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 20)"),
  });

  export const ListUserProjectsV1Response = zod.object({
    projects: zod
      .array(
        zod.object({
          id: zod.number().describe("Project ID (from stardance.hackclub.com)"),
          title: zod.string(),
          description: zod.string().optional(),
          repo_url: zod.url().nullish(),
          demo_url: zod.url().nullish(),
          readme_url: zod.url().nullish(),
          ai_declaration: zod.string().nullish(),
          ship_status: zod.string().nullish(),
          devlog_ids: zod.array(zod.number()).optional(),
          banner_url: zod.url().nullish(),
          created_at: zod.iso.datetime({}).optional(),
          updated_at: zod.iso.datetime({}).optional(),
        }),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * Fetch a ranked list of projects sorted by score (highest first). Defaults to top 10; max 100 per page.
   * @summary List top projects (V2)
   */
  export const listTopProjectsV2QueryLimitMax = 100;

  export const ListTopProjectsV2QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listTopProjectsV2QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 10)"),
  });

  export const ListTopProjectsV2Response = zod.object({
    projects: zod
      .array(
        zod
          .object({
            id: zod
              .number()
              .describe("Project ID (from stardance.hackclub.com)"),
            title: zod.string(),
            description: zod.string().optional(),
            repo_url: zod.url().nullish(),
            demo_url: zod.url().nullish(),
            readme_url: zod.url().nullish(),
            ai_declaration: zod.string().nullish(),
            ship_status: zod.string().nullish(),
            devlog_ids: zod.array(zod.number()).optional(),
            banner_url: zod.url().nullish(),
            created_at: zod.iso.datetime({}).optional(),
            updated_at: zod.iso.datetime({}).optional(),
          })
          .and(
            zod.object({
              username: zod
                .string()
                .nullish()
                .describe("Author's username (without @)"),
              devlog_count: zod.number().optional(),
              total_hours: zod.number().optional(),
              followers: zod.number().optional(),
              sourcecode: zod.url().nullish(),
              superstar: zod.boolean().optional(),
              score: zod.number().nullish(),
              user_id: zod.uuid().optional(),
            }),
          )
          .and(
            zod.object({
              rank: zod
                .number()
                .describe("The overall rank (1 = highest score)"),
            }),
          ),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * Fetch a paginated list of all projects with V2 extended fields. Supports optional search query and limit.
   * @summary List projects (V2)
   */
  export const listProjectsV2QueryLimitMax = 100;

  export const ListProjectsV2QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listProjectsV2QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 20)"),
    query: zod
      .string()
      .optional()
      .describe("Search projects by title or description"),
  });

  export const ListProjectsV2Response = zod.object({
    projects: zod
      .array(
        zod
          .object({
            id: zod
              .number()
              .describe("Project ID (from stardance.hackclub.com)"),
            title: zod.string(),
            description: zod.string().optional(),
            repo_url: zod.url().nullish(),
            demo_url: zod.url().nullish(),
            readme_url: zod.url().nullish(),
            ai_declaration: zod.string().nullish(),
            ship_status: zod.string().nullish(),
            devlog_ids: zod.array(zod.number()).optional(),
            banner_url: zod.url().nullish(),
            created_at: zod.iso.datetime({}).optional(),
            updated_at: zod.iso.datetime({}).optional(),
          })
          .and(
            zod.object({
              username: zod
                .string()
                .nullish()
                .describe("Author's username (without @)"),
              devlog_count: zod.number().optional(),
              total_hours: zod.number().optional(),
              followers: zod.number().optional(),
              sourcecode: zod.url().nullish(),
              superstar: zod.boolean().optional(),
              score: zod.number().nullish(),
              user_id: zod.uuid().optional(),
            }),
          ),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * @summary Get a project (V2)
   */
  export const GetProjectV2Params = zod.object({
    id: zod.number().describe("Project ID"),
  });

  export const GetProjectV2Response = zod
    .object({
      id: zod.number().describe("Project ID (from stardance.hackclub.com)"),
      title: zod.string(),
      description: zod.string().optional(),
      repo_url: zod.url().nullish(),
      demo_url: zod.url().nullish(),
      readme_url: zod.url().nullish(),
      ai_declaration: zod.string().nullish(),
      ship_status: zod.string().nullish(),
      devlog_ids: zod.array(zod.number()).optional(),
      banner_url: zod.url().nullish(),
      created_at: zod.iso.datetime({}).optional(),
      updated_at: zod.iso.datetime({}).optional(),
    })
    .and(
      zod.object({
        username: zod
          .string()
          .nullish()
          .describe("Author's username (without @)"),
        devlog_count: zod.number().optional(),
        total_hours: zod.number().optional(),
        followers: zod.number().optional(),
        sourcecode: zod.url().nullish(),
        superstar: zod.boolean().optional(),
        score: zod.number().nullish(),
        user_id: zod.uuid().optional(),
      }),
    );

  /**
   * Fetch a paginated list of devlogs belonging to a specific project with V2 extended fields.
   * @summary List devlogs for a project (V2)
   */
  export const ListProjectDevlogsV2Params = zod.object({
    id: zod.number().describe("Project ID"),
  });

  export const listProjectDevlogsV2QueryLimitMax = 100;

  export const ListProjectDevlogsV2QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listProjectDevlogsV2QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 20)"),
  });

  export const ListProjectDevlogsV2Response = zod.object({
    devlogs: zod
      .array(
        zod
          .object({
            id: zod
              .number()
              .describe("Devlog ID (from stardance.hackclub.com)"),
            body: zod.string().describe("Devlog text content"),
            comments_count: zod
              .number()
              .optional()
              .describe("Total number of comments"),
            duration_seconds: zod
              .number()
              .optional()
              .describe("Duration in seconds"),
            likes_count: zod.number().optional(),
            scrapbook_url: zod.url().nullish(),
            media: zod
              .array(
                zod.object({
                  url: zod.url().optional(),
                  content_type: zod.string().optional(),
                }),
              )
              .optional()
              .describe("Media attachments (derived from image_urls)"),
            comments: zod
              .array(
                zod.object({
                  id: zod.number().describe("Internal comment ID"),
                  author: zod
                    .object({
                      id: zod.uuid().optional(),
                      display_name: zod.string().optional(),
                      avatar: zod.url().nullish(),
                    })
                    .nullish(),
                  body: zod.string().describe("Comment body"),
                  created_at: zod.iso.datetime({}).optional(),
                  updated_at: zod.iso.datetime({}).optional(),
                }),
              )
              .optional(),
            created_at: zod.iso.datetime({}).optional(),
            updated_at: zod.iso.datetime({}).optional(),
          })
          .and(
            zod.object({
              description: zod.string().optional(),
              image_urls: zod.array(zod.url()).optional(),
              likes: zod.number().optional(),
              views: zod.number().optional(),
              project_id: zod.number().optional(),
              user_id: zod.uuid().optional(),
            }),
          ),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * @summary Get a devlog scoped to a project (V2)
   */
  export const GetProjectDevlogV2Params = zod.object({
    id: zod.number().describe("Project ID"),
    devlog_id: zod.number().describe("Devlog ID"),
  });

  export const GetProjectDevlogV2Response = zod
    .object({
      id: zod.number().describe("Devlog ID (from stardance.hackclub.com)"),
      body: zod.string().describe("Devlog text content"),
      comments_count: zod
        .number()
        .optional()
        .describe("Total number of comments"),
      duration_seconds: zod.number().optional().describe("Duration in seconds"),
      likes_count: zod.number().optional(),
      scrapbook_url: zod.url().nullish(),
      media: zod
        .array(
          zod.object({
            url: zod.url().optional(),
            content_type: zod.string().optional(),
          }),
        )
        .optional()
        .describe("Media attachments (derived from image_urls)"),
      comments: zod
        .array(
          zod.object({
            id: zod.number().describe("Internal comment ID"),
            author: zod
              .object({
                id: zod.uuid().optional(),
                display_name: zod.string().optional(),
                avatar: zod.url().nullish(),
              })
              .nullish(),
            body: zod.string().describe("Comment body"),
            created_at: zod.iso.datetime({}).optional(),
            updated_at: zod.iso.datetime({}).optional(),
          }),
        )
        .optional(),
      created_at: zod.iso.datetime({}).optional(),
      updated_at: zod.iso.datetime({}).optional(),
    })
    .and(
      zod.object({
        description: zod.string().optional(),
        image_urls: zod.array(zod.url()).optional(),
        likes: zod.number().optional(),
        views: zod.number().optional(),
        project_id: zod.number().optional(),
        user_id: zod.uuid().optional(),
      }),
    );

  /**
   * Fetch a paginated list of all devlogs across all projects with V2 extended fields.
   * @summary List all devlogs (V2)
   */
  export const listDevlogsV2QueryLimitMax = 100;

  export const ListDevlogsV2QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listDevlogsV2QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 20)"),
  });

  export const ListDevlogsV2Response = zod.object({
    devlogs: zod
      .array(
        zod
          .object({
            id: zod
              .number()
              .describe("Devlog ID (from stardance.hackclub.com)"),
            body: zod.string().describe("Devlog text content"),
            comments_count: zod
              .number()
              .optional()
              .describe("Total number of comments"),
            duration_seconds: zod
              .number()
              .optional()
              .describe("Duration in seconds"),
            likes_count: zod.number().optional(),
            scrapbook_url: zod.url().nullish(),
            media: zod
              .array(
                zod.object({
                  url: zod.url().optional(),
                  content_type: zod.string().optional(),
                }),
              )
              .optional()
              .describe("Media attachments (derived from image_urls)"),
            comments: zod
              .array(
                zod.object({
                  id: zod.number().describe("Internal comment ID"),
                  author: zod
                    .object({
                      id: zod.uuid().optional(),
                      display_name: zod.string().optional(),
                      avatar: zod.url().nullish(),
                    })
                    .nullish(),
                  body: zod.string().describe("Comment body"),
                  created_at: zod.iso.datetime({}).optional(),
                  updated_at: zod.iso.datetime({}).optional(),
                }),
              )
              .optional(),
            created_at: zod.iso.datetime({}).optional(),
            updated_at: zod.iso.datetime({}).optional(),
          })
          .and(
            zod.object({
              description: zod.string().optional(),
              image_urls: zod.array(zod.url()).optional(),
              likes: zod.number().optional(),
              views: zod.number().optional(),
              project_id: zod.number().optional(),
              user_id: zod.uuid().optional(),
            }),
          ),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * @summary Get a devlog by ID (V2)
   */
  export const GetDevlogV2Params = zod.object({
    id: zod.number().describe("Devlog ID"),
  });

  export const GetDevlogV2Response = zod
    .object({
      id: zod.number().describe("Devlog ID (from stardance.hackclub.com)"),
      body: zod.string().describe("Devlog text content"),
      comments_count: zod
        .number()
        .optional()
        .describe("Total number of comments"),
      duration_seconds: zod.number().optional().describe("Duration in seconds"),
      likes_count: zod.number().optional(),
      scrapbook_url: zod.url().nullish(),
      media: zod
        .array(
          zod.object({
            url: zod.url().optional(),
            content_type: zod.string().optional(),
          }),
        )
        .optional()
        .describe("Media attachments (derived from image_urls)"),
      comments: zod
        .array(
          zod.object({
            id: zod.number().describe("Internal comment ID"),
            author: zod
              .object({
                id: zod.uuid().optional(),
                display_name: zod.string().optional(),
                avatar: zod.url().nullish(),
              })
              .nullish(),
            body: zod.string().describe("Comment body"),
            created_at: zod.iso.datetime({}).optional(),
            updated_at: zod.iso.datetime({}).optional(),
          }),
        )
        .optional(),
      created_at: zod.iso.datetime({}).optional(),
      updated_at: zod.iso.datetime({}).optional(),
    })
    .and(
      zod.object({
        description: zod.string().optional(),
        image_urls: zod.array(zod.url()).optional(),
        likes: zod.number().optional(),
        views: zod.number().optional(),
        project_id: zod.number().optional(),
        user_id: zod.uuid().optional(),
      }),
    );

  /**
   * Fetch a paginated list of all users with V2 extended fields. Supports optional search query.
   * @summary List users (V2)
   */
  export const listUsersV2QueryLimitMax = 100;

  export const ListUsersV2QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listUsersV2QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 20)"),
    query: zod.string().optional().describe("Search users by username or bio"),
  });

  export const ListUsersV2Response = zod.object({
    users: zod
      .array(
        zod
          .object({
            id: zod.uuid().describe("Internal user ID"),
            slack_id: zod.string().nullish(),
            display_name: zod
              .string()
              .describe("Display name (same as username)"),
            avatar: zod.url().nullish().describe("Profile picture URL"),
            project_ids: zod.array(zod.number()).optional(),
            stardust: zod.number().nullish(),
          })
          .and(
            zod.object({
              username: zod.string().optional(),
              user_pfp: zod.url().nullish(),
              bio: zod.string().nullish(),
              banner_url: zod.url().nullish(),
              devlog_count: zod.number().optional(),
              project_count: zod.number().optional(),
              devlog_ids: zod.array(zod.number()).optional(),
              ships: zod.number().optional(),
              votes: zod.number().optional(),
              vote_count: zod.number().optional(),
              like_count: zod.number().optional(),
              slack_url: zod.url().nullish(),
              achievements: zod
                .array(
                  zod.object({
                    slug: zod.string(),
                    name: zod.string(),
                    description: zod.string().nullish(),
                  }),
                )
                .optional(),
              created_at: zod.iso.datetime({}).optional(),
              updated_at: zod.iso.datetime({}).optional(),
            }),
          ),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * @summary Get a user profile (V2)
   */
  export const GetUserV2Params = zod.object({
    username: zod.string().describe('Username (with or without \"@\" prefix)'),
  });

  export const GetUserV2Response = zod
    .object({
      id: zod.uuid().describe("Internal user ID"),
      slack_id: zod.string().nullish(),
      display_name: zod.string().describe("Display name (same as username)"),
      avatar: zod.url().nullish().describe("Profile picture URL"),
      project_ids: zod.array(zod.number()).optional(),
      stardust: zod.number().nullish(),
    })
    .and(
      zod.object({
        username: zod.string().optional(),
        user_pfp: zod.url().nullish(),
        bio: zod.string().nullish(),
        banner_url: zod.url().nullish(),
        devlog_count: zod.number().optional(),
        project_count: zod.number().optional(),
        devlog_ids: zod.array(zod.number()).optional(),
        ships: zod.number().optional(),
        votes: zod.number().optional(),
        vote_count: zod.number().optional(),
        like_count: zod.number().optional(),
        slack_url: zod.url().nullish(),
        achievements: zod
          .array(
            zod.object({
              slug: zod.string(),
              name: zod.string(),
              description: zod.string().nullish(),
            }),
          )
          .optional(),
        created_at: zod.iso.datetime({}).optional(),
        updated_at: zod.iso.datetime({}).optional(),
      }),
    );

  /**
   * Fetch a paginated list of projects belonging to a specific user with V2 extended fields.
   * @summary List projects for a user (V2)
   */
  export const ListUserProjectsV2Params = zod.object({
    username: zod.string().describe('Username (with or without \"@\" prefix)'),
  });

  export const listUserProjectsV2QueryLimitMax = 100;

  export const ListUserProjectsV2QueryParams = zod.object({
    page: zod
      .number()
      .optional()
      .describe("Page number for pagination (default: 1)"),
    limit: zod
      .number()
      .max(listUserProjectsV2QueryLimitMax)
      .optional()
      .describe("Number of results per page (max 100, default: 20)"),
  });

  export const ListUserProjectsV2Response = zod.object({
    projects: zod
      .array(
        zod
          .object({
            id: zod
              .number()
              .describe("Project ID (from stardance.hackclub.com)"),
            title: zod.string(),
            description: zod.string().optional(),
            repo_url: zod.url().nullish(),
            demo_url: zod.url().nullish(),
            readme_url: zod.url().nullish(),
            ai_declaration: zod.string().nullish(),
            ship_status: zod.string().nullish(),
            devlog_ids: zod.array(zod.number()).optional(),
            banner_url: zod.url().nullish(),
            created_at: zod.iso.datetime({}).optional(),
            updated_at: zod.iso.datetime({}).optional(),
          })
          .and(
            zod.object({
              username: zod
                .string()
                .nullish()
                .describe("Author's username (without @)"),
              devlog_count: zod.number().optional(),
              total_hours: zod.number().optional(),
              followers: zod.number().optional(),
              sourcecode: zod.url().nullish(),
              superstar: zod.boolean().optional(),
              score: zod.number().nullish(),
              user_id: zod.uuid().optional(),
            }),
          ),
      )
      .optional(),
    pagination: zod
      .object({
        current_page: zod.number().optional(),
        total_pages: zod.number().optional(),
        total_count: zod.number().optional(),
        next_page: zod.number().nullish(),
      })
      .optional(),
  });

  /**
   * @summary Get all comments for a devlog (V2)
   */
  export const GetDevlogCommentsV2Params = zod.object({
    id: zod.number().describe("Devlog ID"),
  });

  export const GetDevlogCommentsV2ResponseItem = zod.object({
    id: zod.number().describe("Internal comment ID"),
    body: zod.string().describe("Comment body"),
    user: zod
      .object({
        id: zod.uuid(),
        username: zod.string(),
        user_pfp: zod.url().nullish().describe("Profile picture URL"),
      })
      .describe("Minimal public user profile embedded in a comment.")
      .nullish()
      .describe(
        "Author's public profile. Null when the author has no user record.",
      ),
  });
  export const GetDevlogCommentsV2Response = zod.array(
    GetDevlogCommentsV2ResponseItem,
  );

  /**
   * @summary Get all comments across all devlogs of a project (V2)
   */
  export const GetProjectCommentsV2Params = zod.object({
    id: zod.number().describe("Project ID"),
  });

  export const GetProjectCommentsV2ResponseItem = zod.object({
    id: zod.number().describe("Internal comment ID"),
    body: zod.string().describe("Comment body"),
    user: zod
      .object({
        id: zod.uuid(),
        username: zod.string(),
        user_pfp: zod.url().nullish().describe("Profile picture URL"),
      })
      .describe("Minimal public user profile embedded in a comment.")
      .nullish()
      .describe(
        "Author's public profile. Null when the author has no user record.",
      ),
  });
  export const GetProjectCommentsV2Response = zod.array(
    GetProjectCommentsV2ResponseItem,
  );
}
