name: Update example env every commit

on:
  push:
    branches:
      - main
    paths:
      - '**'
      - '!.github/workflows/**'
      - '.example.env'
  workflow_dispatch:

jobs:
  run-bun-script:
    runs-on: ubuntu-slim
    steps:
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.head_ref }}
          token: ${{ secrets.GH_PAT }}
          persist-credentials: true

      - uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Run ftToMDX script
        run: bun run scanEnv
        
      - uses: stefanzweifel/git-auto-commit-action@v7
        with:
          commit_message: "Update .example.env"
